# task1

In [1]:
#1
def num():
    N=int(input("Enter Numerator:"))
    D=int(input("Enter Denominator:"))
    return N,D
N,D=num()
try:
    print("{}/{} is {}".format(N,D,(N/D)))
except ZeroDivisionError:
    print("Cannot divide with zero enter a non zero denominator please.")
    N,D=num()

Enter Numerator:3
Enter Denominator:4
3/4 is 0.75


In [2]:
#2
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in range(len(subjects)):
    for j in range(len(verbs)):
        for k in range(len(objects)):
            print(subjects[i]+verbs[j]+objects[k])

Americans playBaseball
Americans playCricket
Americans watchBaseball
Americans watchCricket
IndiansplayBaseball
IndiansplayCricket
IndianswatchBaseball
IndianswatchCricket


# task 2

In [5]:
import numpy as np

def generate_vandermonde_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = generate_vandermonde_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = generate_vandermonde_matrix(inputvector,no_col_opmat,True)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")



The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

